#######################################
#      Setting custom wallpapers      #
#######################################

- name: Copy wallpapers images
  ansible.builtin.copy:
    src: wallpapers/
    dest: "{{ ansible_user_dir }}/.local/share/backgrounds/"

- name: Set light mode wallpaper
  ansible.builtin.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file://{{ ansible_user_dir }}/.local/share/backgrounds/light-mode-wallpaper.jpg'"

- name: Set dark mode wallpaper
  ansible.builtin.dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file://{{ ansible_user_dir }}/.local/share/backgrounds/dark-mode-wallpaper.jpg'"


#######################################
#     Setting custom keybindings      #
#######################################

# Maximizing & minimizing windows

- name: Set keybinding toggle maximized
  ansible.builtin.dconf:
    key: "/org/gnome/desktop/wm/keybindings/toggle-maximized"
    value: "['<Super>m']"
    state: present


# Switching windows

- name: Set keybinding switch windows
  ansible.builtin.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-windows"
    value: "['<Alt>Tab']"
    state: present

- name: Set keybinding switch windows backward
  ansible.builtin.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-windows-backward"
    value: "['<Shift><Alt>Tab']"
    state: present


# Switching workspaces

- name: Set keybinding switch to workspace right
  ansible.builtin.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-right"
    value: "['<Primary><Super>Right']"
    state: present

- name: Set keybinding switch to workspace left
  ansible.builtin.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-left"
    value: "['<Primary><Super>Left']"
    state: present


# Removing conflicting keybindings

- name: Disable mutter tiling right
  ansible.builtin.dconf:
    key: "/org/gnome/mutter/keybindings/toggle-tiled-right"
    value: "['<Primary><Super>l']"
    state: present

- name: Disable mutter tiling left
  ansible.builtin.dconf:
    key: "/org/gnome/mutter/keybindings/toggle-tiled-left"
    value: "['<Primary><Super>h']"
    state: present

- name: Get ibus emoji picker keybind
  ansible.builtin.shell: gsettings get org.freedesktop.ibus.panel.emoji hotkey
  register: emoji_picker_key
  changed_when: false

- name: Disable ibus emoji picker
  ansible.builtin.command: gsettings set org.freedesktop.ibus.panel.emoji hotkey "[]"
  when: emoji_picker_key.stdout != "@as []"


##########################################
#    Disabling middle-click to paste     #
#                on Xorg                 #
##########################################

# The following executable was compiled from the code available at
# https://github.com/milaq/XMousePasteBlock

- name: Copy xmousepasteblock executable to remote bin path
  become: true
  ansible.builtin.copy:
    src: "{{ xmousepasteblock_executable }}"
    dest: "/usr/bin/"

- name: Copy xmousepasteblock autostart entry
  ansible.builtin.copy:
    src: "{{ xmousepasteblock_autostart_entry }}"
    dest: "{{ ansible_user_dir }}/.config/autostart/"


##########################################
#      Enable systemd boot messages      # 
##########################################

- name: Set kernelstub to show systemd boot messages
  ansible.builtin.shell:
    cmd: sudo kernelstub --delete-options "quiet systemd.show_status=false splash" && sudo kernelstub --add-options "systemd.show_status=true"
  when:
    ( ansible_proc_cmdline.quiet is defined and ansible_proc_cmdline.quiet == true ) or
    ( ansible_proc_cmdline.splash is defined and ansible_proc_cmdline.splash == true ) or
    ansible_proc_cmdline['systemd.show_status'] is not defined or
    ansible_proc_cmdline['systemd.show_status'] == "false"