#######################################
#      Setting custom wallpapers      #
#######################################

- name: Copy wallpapers images
  ansible.builtin.copy:
    src: wallpapers/
    dest: "{{ ansible_user_dir }}/.local/share/backgrounds/"

- name: Set light mode wallpaper
  ansible.builtin.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file://{{ ansible_user_dir }}/.local/share/backgrounds/light-mode-wallpaper.jpg'"

- name: Set dark mode wallpaper
  ansible.builtin.dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file://{{ ansible_user_dir }}/.local/share/backgrounds/dark-mode-wallpaper.jpg'"


