- name: Install dependencies
  become: true
  ansible.builtin.package:
    state: present
    name:
      - apt-transport-https
      - curl
      - gpg
      - wget

- name: Add VSCode repo & keys to apt
  ansible.builtin.script:
    cmd: "{{ playbook_dir }}/vscode.sh"
  args:
    creates: /etc/apt/sources.list.d/vscode.list

- name: Add Brave Browser repo & keys to apt
  ansible.builtin.script:
    cmd: "{{ playbook_dir }}/brave-browser.sh"
  args:
    creates: /etc/apt/sources.list.d/brave-browser-release.list

- name: Download ZeroTier install script
  ansible.builtin.script:
    cmd: "curl -s https://install.zerotier.com -o zerotier-install.sh"
  args:
    creates: "{{ playbook_dir }}/zerotier-install.sh"

- name: Download docker install script
  ansible.builtin.script:
    cmd: "curl -fsSL https://get.docker.com -o docker-install.sh"
  args:
    creates: "{{ playbook_dir }}/docker-install.sh"

- name: Run ZeroTier install script
  ansible.builtin.script:
    cmd: "{{ playbook_dir }}/zerotier-install.sh"
  args:
    creates: ""

- name: Run docker install script
  ansible.builtin.script:
    cmd: "{{ playbook_dir }}/docker-install.sh"
  args:
    creates: ""

- name: Install apt packages
  become: true
  ansible.builtin.package:
    state: present
    name:
      - ark
      - arp-scan
      - brave-browser
      - btop
      - build-essential
      - cmake
      - code
      - containerd.io
      - dfu-util
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
      - entr
      - gimp
      - gnome-shell-extension-manager
      - gparted
      - htop
      - inkscape
      - kdenlive
      - keepassxc
      - kernelstub
      - lutris
      - nala
      - neofetch
      - nmap
      - nodejs
      - nvtop
      - obs-studio
      - okular
      - pip
      - powertop
      - remmina
      - steam
      - timeshift
      - tmux
      - virt-manager
      - vlc
      - xournalpp

- name: install Huion HS64 drivers
  become: true
  ansible.builtin.package:
    deb:
      "https://driverdl.huion.com/driver/Linux/HuionTablet_LinuxDriver_v15.0.0.162.x86_64.deb"

- name: install GitKraken
  become: true
  ansible.builtin.package:
    deb:
      "https://release.gitkraken.com/linux/gitkraken-amd64.deb"

- name: Install Vesktop flatpak
  community.general.flatpak:
    method: user
    state: present
    name: dev.vencord.Vesktop

- name: Install MMEX flatpak
  community.general.flatpak:
    method: user
    state: present
    name: org.moneymanagerex.MMEX

- name: Install Prism Launcher flatpak
  community.general.flatpak:
    method: user
    state: present
    name: org.prismlauncher.PrismLauncher

- name: Install pip packages
  ansible.builtin.pip:
    state: latest
    name:
      - pyautogui

- name: Check the number of nala sources
  ansible.builtin.shell: cat /etc/apt/sources.list.d/nala-sources.list | grep -c "deb"
  register: nala_sources
  changed_when: false
  args:
    # Only runs when the nala sources file exists
    removes: /etc/apt/sources.list.d/nala-sources.list

- name: Run nala fetch
  ansible.builtin.shell:
    cmd: echo "y" | sudo nala fetch --auto --fetches 16
  when: nala_sources.stdout | int < 16