- name: Install Pop OS! packages
  ansible.builtin.package:
    state: present
    name:
      - ark
      - gimp
      - gnome-shell-extension-manager
      - htop
      - inkscape
      - kdenlive
      - keepassxc
      - lutris
      - nala
      - neofetch
      - nmap
      - nodejs
      - nvtop
      - okular
      - pip
      - steam
      - timeshift
      - tmux
      - virt-manager
      - xournalpp

- name: Run nala fetch
  ansible.builtin.command: sudo nala fetch --auto --fetches 16