- name: Install Pop OS! packages
  ansible.builtin.package:
    state: present
    name:
      - ark
      - entr
      - gimp
      - gnome-shell-extension-manager
      - htop
      - inkscape
      - kdenlive
      - keepassxc
      - lutris
      - nala
      - neofetch
      - nmap
      - nodejs
      - nvtop
      - okular
      - pip
      - powertop
      - steam
      - timeshift
      - tmux
      - virt-manager
      - xournalpp

- name: Check the number of nala sources
  ansible.builtin.shell: cat /etc/apt/sources.list.d/nala-sources.list | grep -c "deb"
  register: nala_sources

- name: Run nala fetch
  ansible.builtin.shell:
    cmd: echo "y" | sudo nala fetch --auto --fetches 16
  when: nala_sources.stdout | int < 16